// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sales.Infrastructure.DataContext;

#nullable disable

namespace Sales.Infrastructure.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260709050320_Added_GoodsReceipt_Entities")]
    partial class Added_GoodsReceipt_Entities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sales.Domain.Entities.Customer.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasComment("Địa chỉ giao hàng / liên hệ, tối đa 250 ký tự.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã khách hàng nội bộ, duy nhất, tối đa 50 ký tự.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Địa chỉ email liên hệ, tối đa 100 ký tự.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = đã xóa mềm, không hiển thị trong query thông thường.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Tên khách hàng, tối đa 150 ký tự.");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Số điện thoại liên hệ, tối đa 20 ký tự.");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerGroupId");

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasComment("Thông tin khách hàng mua hàng trong hệ thống bán lẻ.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Customer.CustomerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã nhóm khách hàng nội bộ, duy nhất, tối đa 50 ký tự.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = đã xóa mềm, không hiển thị trong query thông thường.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Tên nhóm khách hàng, tối đa 150 ký tự.");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CustomerGroups", null, t =>
                        {
                            t.HasComment("Nhóm khách hàng dùng để phân loại khách hàng theo chính sách giá, chiết khấu.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã phiếu nhập kho (Ví dụ: GR-YYMM-00001).");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm.");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Ghi chú cho phiếu nhập kho.");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã chứng từ gốc để hiển thị nhanh.");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Trạng thái: 0=Draft, 1=Completed, 2=Cancelled.");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Tổng số lượng thực tế của tất cả các dòng sản phẩm.");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Loại phiếu: 1=Purchase, 2=Return, 3=Transfer.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GoodsReceipts", null, t =>
                        {
                            t.HasComment("Bảng lưu trữ thông tin phiếu nhập kho (Header).");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.GoodsReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<decimal>("ActualQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Số lượng thực tế nhập kho.");

                    b.Property<decimal>("ConversionRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasComment("Tỷ lệ quy đổi so với đơn vị cơ bản lúc nhập.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Số lượng dự kiến từ chứng từ gốc.");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid")
                        .HasComment("FK → GoodsReceipts.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm.");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasComment("Ghi chú tại dòng.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Products.");

                    b.Property<Guid>("UoMId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Units.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptId");

                    b.ToTable("GoodsReceiptLines", null, t =>
                        {
                            t.HasComment("Dòng chi tiết trong phiếu nhập kho.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<int>("AllocatedQty")
                        .HasColumnType("integer")
                        .HasComment("Số lượng hàng đã giữ chỗ (Sales Order Confirmed).");

                    b.Property<int>("AvailableQty")
                        .HasColumnType("integer")
                        .HasComment("Số lượng khả dụng dùng để bán (Available = OnHandQty - AllocatedQty).");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = bản ghi đã bị xóa mềm.");

                    b.Property<int>("OnHandQty")
                        .HasColumnType("integer")
                        .HasComment("Số lượng vật lý đang có trong kho.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Products. Sản phẩm của số dư này.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryBalances", null, t =>
                        {
                            t.HasComment("Bảng số dư tồn kho của sản phẩm, dùng để kiểm soát tồn kho tức thời.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<int>("BaseQty")
                        .HasColumnType("integer")
                        .HasComment("Số lượng quy đổi theo đơn vị cơ bản (cộng/trừ).");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Products.");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Ghi chú/Lý do.");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã chứng từ tham chiếu (VD: PO-123, SO-456).");

                    b.Property<int>("TransactedQty")
                        .HasColumnType("integer")
                        .HasComment("Số lượng giao dịch theo đơn vị lúc thao tác.");

                    b.Property<Guid>("TransactedUomId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Units. Đơn vị thao tác.");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Loại giao dịch: 1=Inbound, 2=Outbound, 3=AdjustmentIn, 4=AdjustmentOut, 5=OtherIssue.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactedUomId");

                    b.ToTable("InventoryTransactions", null, t =>
                        {
                            t.HasComment("Bảng thẻ kho ghi nhận lịch sử giao dịch (Nhập, Xuất, Điều chỉnh).");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.ProductCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ hiệu lực của mức giá vốn.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm.");

                    b.Property<decimal>("MovingAverageCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá vốn bình quân theo đơn vị cơ bản.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Products.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCosts", null, t =>
                        {
                            t.HasComment("Lịch sử giá vốn bình quân gia quyền (Moving Average Cost) của sản phẩm.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Order.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng tạo đơn hàng.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ tạo bản ghi (UTC).");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Customers. Khách hàng đặt đơn.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Số tiền chiết khấu toàn đơn.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = đã xóa mềm, không hiển thị trong query thông thường.");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasComment("Ghi chú nội bộ hoặc yêu cầu đặc biệt của khách hàng.");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ đặt hàng (UTC).");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã số đơn hàng tự sinh, duy nhất. Ví dụ: ORD-20260708-001.");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasComment("Trạng thái xử lý đơn hàng: 0=Draft (Nháp), 1=Confirmed (Đã xác nhận), 2=Completed (Hoàn thành), 3=Cancelled (Đã hủy).");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasComment("Trạng thái thanh toán: 0=Unpaid (Chưa thanh toán), 1=PartiallyPaid (Thanh toán một phần), 2=FullyPaid (Đã thanh toán đủ).");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Tổng tiền hàng trước chiết khấu và thuế (= Σ TotalAmount của các dòng chi tiết).");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Thuế VAT hoặc các loại thuế khác tính trên đơn hàng.");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Thành tiền cuối cùng = SubTotal - DiscountAmount + TaxAmount.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng cập nhật lần cuối.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ cập nhật gần nhất (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasComment("Đơn hàng bán lẻ. Mỗi đơn gắn với một khách hàng và chứa danh sách mặt hàng đã mua.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Order.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<decimal>("ConversionRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasComment("Tỷ lệ quy đổi sang đơn vị cơ bản. Mặc định = 1.");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Số tiền chiết khấu dòng = UnitPrice × Quantity × DiscountPercentage / 100.");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("double precision")
                        .HasComment("Phần trăm chiết khấu dòng (0–100).");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = dòng đã bị xóa mềm.");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Orders. Đơn hàng cha chứa dòng này.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Products. Sản phẩm được bán trong dòng này.");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Số lượng bán tính theo đơn vị tính đã chọn.");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Thành tiền dòng = UnitPrice × Quantity − DiscountAmount.");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Units. Đơn vị tính được chọn cho dòng này.");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Đơn giá bán tại thời điểm lập đơn (VNĐ). Chốt cứng, không thay đổi theo giá sản phẩm sau.");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("OrderDetails", null, t =>
                        {
                            t.HasComment("Chi tiết dòng mặt hàng trong đơn hàng. Mỗi dòng là một sản phẩm ở một đơn vị tính cụ thể.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã nhóm hàng nội bộ, duy nhất, tối đa 50 ký tự.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng tạo bản ghi.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ tạo bản ghi (UTC).");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Mô tả thêm về nhóm hàng (tuỳ chọn).");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = đã xóa mềm, không hiển thị trong query thông thường.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Tên nhóm hàng, tối đa 150 ký tự.");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("Trạng thái: 1 = đang sử dụng, 0 = đã ẩn/ngừng dùng.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng cập nhật lần cuối.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ cập nhật gần nhất (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasComment("Nhóm hàng (danh mục sản phẩm). Dùng để phân loại sản phẩm theo ngành hàng.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã vạch của đơn vị cơ bản (tuỳ chọn), tối đa 50 ký tự.");

                    b.Property<Guid>("BaseUnitId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Units. Đơn vị tính cơ bản (ví dụ: Chai, Hộp).");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Categories. Nhóm hàng của sản phẩm.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã sản phẩm nội bộ, duy nhất, tối đa 50 ký tự.");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá vốn / chi phí mua vào theo đơn vị cơ bản (VNĐ).");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng tạo bản ghi.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ tạo bản ghi (UTC).");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Mô tả chi tiết hoặc ghi chú về sản phẩm (tuỳ chọn).");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = đã xóa mềm. Dữ liệu vẫn giữ lại để hiển thị trong lịch sử đơn hàng và báo cáo.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Tên sản phẩm, tối đa 150 ký tự.");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá bán lẻ mặc định theo đơn vị cơ bản (VNĐ).");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("Trạng thái: 1 = đang hoạt động, 0 = ngừng kinh doanh.");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasComment("Tồn kho hiện tại tính theo đơn vị cơ bản. Cập nhật tự động khi có giao dịch.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng cập nhật lần cuối.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ cập nhật gần nhất (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", null, t =>
                        {
                            t.HasComment("Sản phẩm hàng hóa trong hệ thống bán hàng. Mỗi sản phẩm thuộc một nhóm hàng và có một đơn vị tính cơ bản.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.ProductUnitConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<Guid>("AlternativeUnitId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Units. Đơn vị tính phụ (ví dụ: Thùng).");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã vạch riêng của đơn vị phụ (tuỳ chọn), duy nhất, tối đa 50 ký tự.");

                    b.Property<decimal>("ConversionRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasComment("Tỷ lệ quy đổi: số lượng đơn vị cơ bản = 1 đơn vị phụ. Ví dụ: 12 (1 Thùng = 12 Chai).");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = đã xóa mềm.");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá bán riêng khi bán theo đơn vị phụ (tuỳ chọn, VNĐ). Null = tự tính từ giá cơ bản × ConversionRate.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasComment("FK → Products. Sản phẩm sở hữu bản ghi quy đổi này.");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeUnitId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductUnitConversions", null, t =>
                        {
                            t.HasComment("Cấu hình quy đổi đơn vị tính phụ cho sản phẩm. Ví dụ: 1 Thùng = 12 Chai.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Khóa chính (UUID).");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã viết tắt đơn vị tính, duy nhất, tối đa 50 ký tự. Ví dụ: CHI, THG.");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng tạo bản ghi.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ tạo bản ghi (UTC).");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng thực hiện xóa mềm.");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ xóa mềm (UTC). Null nếu chưa xóa.");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Mô tả thêm về đơn vị tính (tuỳ chọn).");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Cờ xóa mềm: true = đã xóa mềm, không hiển thị trong query thông thường.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Tên đơn vị tính. Ví dụ: Chai, Thùng, Kg.");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("Trạng thái: 1 = đang sử dụng, 0 = đã ẩn/ngừng dùng.");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID người dùng cập nhật lần cuối.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày giờ cập nhật gần nhất (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Units", null, t =>
                        {
                            t.HasComment("Đơn vị tính dùng trong quản lý sản phẩm và giao dịch. Ví dụ: Cái, Hộp, Thùng, Kg, Lít.");
                        });
                });

            modelBuilder.Entity("Sales.Domain.Entities.Customer.Customer", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Customer.CustomerGroup", "CustomerGroup")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerGroup");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.GoodsReceiptLine", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Inventory.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.InventoryBalance", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.InventoryTransaction", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sales.Domain.Entities.Product.Unit", "TransactedUom")
                        .WithMany()
                        .HasForeignKey("TransactedUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("TransactedUom");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.ProductCost", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Order.Order", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Customer.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Order.OrderDetail", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Order.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sales.Domain.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sales.Domain.Entities.Product.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.Product", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Product.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sales.Domain.Entities.Product.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.ProductUnitConversion", b =>
                {
                    b.HasOne("Sales.Domain.Entities.Product.Unit", "AlternativeUnit")
                        .WithMany()
                        .HasForeignKey("AlternativeUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sales.Domain.Entities.Product.Product", "Product")
                        .WithMany("Conversions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativeUnit");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Customer.CustomerGroup", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Inventory.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Order.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sales.Domain.Entities.Product.Product", b =>
                {
                    b.Navigation("Conversions");
                });
#pragma warning restore 612, 618
        }
    }
}
